# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scc', '0002_uhome_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emial', models.EmailField(max_length=254)),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skill4', models.CharField(max_length=50)),
                ('skill5', models.CharField(max_length=50)),
                ('skill6', models.CharField(max_length=50)),
                ('skill7', models.CharField(max_length=50)),
                ('skill8', models.CharField(max_length=50)),
                ('precent1', models.CharField(max_length=50)),
                ('precent2', models.CharField(max_length=50)),
                ('precent3', models.CharField(max_length=50)),
                ('precent4', models.CharField(max_length=50)),
                ('precent5', models.CharField(max_length=50)),
                ('precent6', models.CharField(max_length=50)),
                ('precent7', models.CharField(max_length=50)),
                ('precent8', models.CharField(max_length=50)),
                ('study1', models.CharField(max_length=50)),
                ('study2', models.CharField(max_length=50)),
                ('study3', models.CharField(max_length=50)),
                ('study4', models.CharField(max_length=50)),
                ('study5', models.CharField(max_length=50)),
                ('study6', models.CharField(max_length=50)),
                ('study7', models.CharField(max_length=50)),
                ('study8', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='uhome_admin',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
